// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SecurityManagement.Infrastructure.Persistence;

#nullable disable

namespace SecurityManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SecurityManagementDbContext))]
    [Migration("20240919055230_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ACM")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SecurityManagement.Domain.Entities.AuthorizablePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("GroupId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("AuthorizablePermissions", "ACM");
                });

            modelBuilder.Entity("SecurityManagement.Domain.Entities.AuthorizablePermissionGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("AuthorizablePermissionGroups", "ACM");
                });

            modelBuilder.Entity("SecurityManagement.Domain.Entities.AuthorizableRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("AuthorizableRoles", "ACM");
                });

            modelBuilder.Entity("SecurityManagement.Domain.Entities.RolePermission", b =>
                {
                    b.Property<long>("AuthorizableRoleId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("AuthorizablePermissionId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("AuthorizableRoleId", "AuthorizablePermissionId");

                    b.HasIndex("AuthorizablePermissionId");

                    b.ToTable("RolePermissions", "ACM");
                });

            modelBuilder.Entity("SecurityManagement.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<byte>("Gender")
                        .HasColumnType("NUMBER(3)");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(false);

                    b.Property<byte>("MaritalStatus")
                        .HasColumnType("NUMBER(3)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("ProfilePictureUri")
                        .HasMaxLength(2048)
                        .HasColumnType("NCLOB");

                    b.Property<byte>("Status")
                        .HasColumnType("NUMBER(3)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("PhoneNumber");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", "ACM");
                });

            modelBuilder.Entity("SecurityManagement.Domain.Entities.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("AuthorizableRoleId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("UserId", "AuthorizableRoleId");

                    b.HasIndex("AuthorizableRoleId");

                    b.ToTable("UserRoles", "ACM");
                });

            modelBuilder.Entity("SecurityManagement.Domain.Entities.AuthorizablePermission", b =>
                {
                    b.HasOne("SecurityManagement.Domain.Entities.AuthorizablePermissionGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Fk_AuthPermissions_Category");
                });

            modelBuilder.Entity("SecurityManagement.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("SecurityManagement.Domain.Entities.AuthorizablePermission", null)
                        .WithMany()
                        .HasForeignKey("AuthorizablePermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Fk_RolePermissions_AuthPermission");

                    b.HasOne("SecurityManagement.Domain.Entities.AuthorizableRole", null)
                        .WithMany()
                        .HasForeignKey("AuthorizableRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Fk_RolePermissions_AuthRole");
                });

            modelBuilder.Entity("SecurityManagement.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("SecurityManagement.Domain.Entities.AuthorizableRole", null)
                        .WithMany()
                        .HasForeignKey("AuthorizableRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurityManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
